import test from 'node:test';
import assert from 'node:assert/strict';
import {createCapsule,readCapsule,mergeCapsule,continuationURL,HANDOFF_TTL} from '../assets/handoff.js';
import {emptyState} from '../assets/state.js';
const course={id:'fundamentos-ciberseguridad',modules:Array.from({length:32},(_,i)=>{const n=String(i+1).padStart(2,'0');return{id:'M'+n,labs:[...'ABC'].map(x=>({id:'L'+n+x}))};})};
const now=()=>Math.floor(Date.now()/1000);
const unpack=v=>JSON.parse(Buffer.from(v,'base64url').toString('utf8'));
const pack=v=>Buffer.from(JSON.stringify(v)).toString('base64url');
function seed(){const s=emptyState(course);s.modules.M05={read:true,quiz:true,bookmarked:true,notes:'PRIVATE NOT FOR THE LINK'};s.labs.L05A={steps:[true,true,true,true,true],done:true};s.labs.L05B.steps[0]=true;s.lastRoute='#/modulo/M05/practica/L05B';return s;}
test('round trip carries all progress bits and continuation, not notes',()=>{const s=seed(),c=readCapsule(createCapsule(course,s,'en'),course),result=mergeCapsule(course,emptyState(course),c);assert.equal(result.modules.M05.read,true);assert.equal(result.labs.L05A.done,true);assert.equal(result.labs.L05B.steps[0],true);assert.equal(result.lastRoute,s.lastRoute);assert.equal(c.language,'en');assert.equal(result.modules.M05.notes,'');assert.ok(!JSON.stringify(unpack(createCapsule(course,s))).includes('PRIVATE'));});
test('merging preserves receiving notes and earlier achievements',()=>{const local=emptyState(course);local.modules.M01.read=true;local.modules.M05.notes='receiver note';const x=mergeCapsule(course,local,readCapsule(createCapsule(course,seed()),course));assert.equal(x.modules.M01.read,true);assert.equal(x.modules.M05.notes,'receiver note');assert.equal(local.modules.M05.quiz,false);});
test('all 160 milestones can travel under 2048 URL characters',()=>{const s=emptyState(course);for(const m of Object.values(s.modules))Object.assign(m,{read:true,quiz:true,bookmarked:true});for(const l of Object.values(s.labs))Object.assign(l,{steps:[true,true,true,true,true],done:true});const url=continuationURL('https://example.test/campus/',course,s,'en');assert.ok(url.length<2048);assert.equal(mergeCapsule(course,emptyState(course),readCapsule(new URL(url).hash.slice(11),course)).labs.L32C.done,true);});
test('query credentials and tracking are not carried to another device',()=>{const u=new URL(continuationURL('https://example.test/?token=not-a-real-token&utm_source=test#/modulo/M01',course,seed(),'en'));assert.equal(u.search,'?lang=en');assert.ok(u.hash.startsWith('#/transfer/'));});
test('a normal link format is not accepted as an authentication token',()=>assert.throws(()=>readCapsule('not.a.jwt',course)));
test('external continuation is rejected',()=>{const x=unpack(createCapsule(course,seed()));x.r='https://evil.test';assert.throws(()=>readCapsule(pack(x),course));});
test('unknown payload properties are rejected',()=>{const x=unpack(createCapsule(course,seed()));x.email='student@example.test';assert.throws(()=>readCapsule(pack(x),course));});
test('expired snapshot rejected without mutation',()=>{const s=seed(),before=JSON.stringify(s),text=createCapsule(course,s,'es',now()-HANDOFF_TTL-1);assert.throws(()=>readCapsule(text,course));assert.equal(JSON.stringify(s),before);});
test('future timestamp rejected',()=>assert.throws(()=>readCapsule(createCapsule(course,seed(),'es',now()+1000),course)));
test('excessive lifetime rejected',()=>{const x=unpack(createCapsule(course,seed()));x.x+=1;assert.throws(()=>readCapsule(pack(x),course));});
test('unknown schema rejected',()=>{const x=unpack(createCapsule(course,seed()));x.v=99;assert.throws(()=>readCapsule(pack(x),course));});
test('wrong course rejected',()=>{const x=unpack(createCapsule(course,seed()));x.c='another-course';assert.throws(()=>readCapsule(pack(x),course));});
test('unsupported language rejected',()=>assert.throws(()=>createCapsule(course,seed(),'de')));
test('malformed flag size rejected',()=>{const x=unpack(createCapsule(course,seed()));x.m='AA';assert.throws(()=>readCapsule(pack(x),course));});
test('incoherent complete lab rejected',()=>{const x=unpack(createCapsule(course,seed()));const bytes=Buffer.from(x.l,'base64url');bytes[0]=32;x.l=bytes.toString('base64url');assert.throws(()=>readCapsule(pack(x),course));});
test('invalid base URL protocol rejected',()=>assert.throws(()=>continuationURL('javascript:alert(1)',course,seed(),'es')));
test('plain HTTP outside local tests rejected',()=>assert.throws(()=>continuationURL('http://example.test',course,seed(),'es')));
test('credentials in URL rejected',()=>assert.throws(()=>continuationURL('https://user:pass@example.test/',course,seed(),'es')));
test('catalogue changes fail closed instead of misapplying position bits',()=>{const other=structuredClone(course);other.modules.reverse();assert.throws(()=>createCapsule(other,seed()));});
test('oversized capsule rejected before parse',()=>assert.throws(()=>readCapsule('A'.repeat(2000),course)));
test('foreign lab resume rejected',()=>{const x=unpack(createCapsule(course,seed()));x.r='#/modulo/M05/practica/L06A';assert.throws(()=>readCapsule(pack(x),course));});
test('corrupt UTF-8 rejected',()=>assert.throws(()=>readCapsule(Buffer.from([255,255]).toString('base64url'),course)));
