"""Reviewed English titles and formative checks, applied to the Spanish source.
Run explicitly during editorial preparation, not on learners' devices.
"""
from pathlib import Path
import sys,json
HERE=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(HERE))
from build import collect
c=collect()
rows=[
('Assessment, safe working and the lab','Before copying a command from a guide, what must you confirm?',['That the command worked on another machine.','The machine, identity, path, authorized scope and expected effect.','That the terminal has a recognizable colour.'],'Another person must be able to reproduce the intervention from your activity log, without spoken instructions. Keep that log outside the machine you will restore.'),
('Information representation and hardware','Two files display the same text but have different SHA-256 hashes. What can you conclude?',['Someone must have tampered with the machine.','The SHA-256 algorithm has stopped working.','The bytes differ; I need to check the encoding and line endings.'],'Explain a size difference using the observed bytes. A different hash shows a difference in binary content, not malicious intent or authorship.'),
('OS architecture, boot and execution','Why might a service continue running after you close your terminal?',['Its lifecycle may be managed by the system rather than that session.','Every service is a process without a user.','Closing a terminal never terminates processes.'],'Represent the relationships without confusing a window, a shell, a process and a service. Do not close other users\' processes to demonstrate the difference.'),
('Terminal workflow, documentation and Git','A script works in your terminal but fails when scheduled. What should you check first?',['Automatically run the entire task as administrator.','Identity, working directory, PATH, environment, dependencies and permissions.','The console colour.'],'Repeat the task from a new directory and another session. It is not reproducible yet if it depends on an undocumented variable or path.'),
('Linux: shell, directories and files','Why does an inventory change when its output is saved inside the source directory?',['Because hidden files can never be counted.','Because a relative path is always incorrect.','The output itself adds a file to the set being measured.'],'Deliver names, sizes and hashes with the scope declared. Explain which metadata are outside that scope: a content hash does not validate ACLs, ownership or the entire history of a file.'),
('Linux: text, search and pipelines','How can you reliably search for a domain in JSON events?',['Parse the JSON and compare the normalized field using the defined matching rules.','Search for the string anywhere in the file and accept every result.','Delete lines I do not understand before counting.'],'Distinguish zero matches, invalid input and failed execution. Preserve the original so that every transformation can be reconstructed.'),
('Linux: users, permissions and privileges','A file\'s permission bits look correct, but reading is denied. What else should you check?',['Make the entire system directory globally writable.','Effective identity, parent directories, ACLs and additional controls.','Only the file extension.'],'Record the previous state, the smallest necessary change and the recovery test. A permissions report alone does not demonstrate privilege escalation.'),
('Linux: processes, packages, services and scheduled tasks','Do active and enabled at boot describe the same state?',['Yes, they are synonyms on every system.','They only matter for services with a graphical interface.','No: one describes current execution and the other startup configuration.'],'Before repeatedly restarting a service, identify the cause and preserve the initial observation. Record a functional test after any update.'),
('Linux: storage, backups and recovery','What best demonstrates that a backup can be recovered?',['A verified restoration, with time, data and permissions checked.','A recent timestamp on the backup file.','Keeping the backup on the same disk as the original.'],'Distinguish the agreed objective from the measured result. Store the information needed to recover an encrypted volume separately and securely.'),
('Linux: host networking and exposure control','The name resolves, but the application does not respond. What does this mean?',['The fault can only be in DNS.','Name resolution works; routing, transport, TLS and the application still need checking.','All connectivity has been proven.'],'Check one permitted and one denied flow while retaining access to the recovery console. Do not disable the entire firewall as a diagnostic method.'),
('Bash: structured programming','What most improves the reliability of a Bash automation?',['Enable one option and assume every failure is handled.','Concatenate user input into an arbitrary command.','An explicit contract, correct quoting, and tests for errors and edge cases.'],'An option such as set -e does not replace testing or a complete error-handling policy. Explain what a trap cleans up and why it affects only the script\'s own temporary files.'),
('Bash: robust and safe automation','Does a dry-run mode alone prove that a script makes no changes?',['No; its code paths and observed effects must be checked.','Yes, provided the option is named dry-run.','Only when it runs with maximum privileges.'],'Run the test twice and compare state, not just messages. Keep a regression test for every corrected error.'),
('Windows: architecture and GUI administration','What should a Windows administration record include?',['Only whether the desktop uses a light theme.','Edition, build, architecture, patches, engine and relevant modules.','Only the Windows product name.'],'Do not declare an executable trustworthy based only on its name. Relate its location, origin, signature where applicable, identity and execution context.'),
('Windows: CMD and native utilities','A utility returns a non-zero exit code. What should you do?',['Always mark the entire operation as a fatal failure.','Ignore the code because text appeared on screen.','Check its documented meaning and verify the result.'],'Explain why a non-zero return code does not mean the same thing for every tool. In PowerShell, use the full executable name when an alias could be confused with it.'),
('Windows: BAT and legacy automation','What is a sound reason to migrate a batch script to PowerShell?',['A need for structured data, stronger validation and verifiable maintenance.','Both languages interpret every command in the same way.','Migration removes the need for tests and error handling.'],'Do not translate each line mechanically. Keep a test suite that describes the behaviour the program must retain.'),
('PowerShell: language, objects and data','When should Format-Table be used?',['Always before ConvertTo-Json.','At the end of output intended for human reading, not before exporting data.','Before any filtering of objects.'],'Distinguish Windows PowerShell 5.1, PowerShell 7 and Windows-specific modules. Execution policy is not a security boundary.'),
('PowerShell: Windows administration','What is still needed even when a command supports -WhatIf?',['Nothing: WhatIf creates a complete backup.','Disable UAC to make the preview realistic.','A preserved prior state and a verified rollback procedure.'],'Demonstrate both functionality and restrictions after the change. Do not export the entire Registry, personal profiles or secrets to solve a narrowly scoped task.'),
('Windows: identity, networking and remote access','What demonstrates that remote access has been correctly delegated?',['The identity can perform the intended actions and is denied unauthorized actions.','Any encrypted connection can be established.','Every machine is included in a global trusted-host list.'],'Document the delegation scope and the closure of temporary access. A demonstration using exported data does not validate administration of a real domain.'),
('Windows: events, protection and recovery','You cannot find an expected event. What is the appropriate conclusion?',['The machine must be clean.','I must check coverage, configuration, permissions and retention before concluding.','The action did not happen.'],'Record what was enabled, what was not visible and what may have been lost through retention. Do not print recovery protectors in your notebook or Git.'),
('macOS: Darwin, APFS, GUI and terminal','What should be documented when copying a file on macOS?',['Only whether the icon still looks similar.','Nothing, as long as the extension stays the same.','Which content and metadata were preserved, including ACLs or attributes where relevant.'],'Explain what you actually preserved. A file hash does not verify all its attributes or the integrity of an entire application.'),
('macOS: zsh, files and automation','The same script fails only on macOS. What should you check?',['Interpreter, version, BSD/GNU utilities, environment, dependencies and permissions.','Assume that all Linux options are available.','Grant Full Disk Access without diagnosing the problem.'],'Document every observed difference. A third-party package manager needs provenance, inventory and maintenance; it is not automatically part of the base platform.'),
('macOS: users, services, networking and launchd','A launchd task works manually but not when scheduled. What may differ?',['Only the output filename.','User, scope, paths, environment and effective permissions.','Nothing: the two executions always have the same context.'],'Remove only the exercise task and verify the resulting state. Do not assume that your interactive Terminal environment is available to an automated task.'),
('macOS: security controls and evidence','A tool cannot access a protected folder. What should you do?',['Disable platform protections by default.','Conclude that the file does not exist.','Diagnose permissions and privacy controls, granting only the necessary authorization.'],'Distinguish non-compliant, not applicable and not verifiable. When a protection blocks an action, investigate the minimum authorization required rather than disabling protection globally.'),
('Networking, remote access and file transfers','Why is knowing that a transfer is encrypted not enough?',['Destination, identity, authorization and integrity must also be verified.','Encryption makes permissions unnecessary.','Every remote protocol preserves the same metadata.'],'Record source, destination, purpose and session closure. Do not disable identity checks to resolve an unexpected mismatch.'),
('Web services, TLS and secure operation','What should a functional health check verify?',['Only that the domain is registered.','A useful service response, not merely an open port.','Only that the process has a PID.'],'Demonstrate a useful service, limited permissions, logging and recovery. This static campus does not need to expose a shell or mount the Docker socket.'),
('Cross-platform automation and containers','Can a static Pages website administer a learner\'s VM by itself?',['Yes, simply by including a Run button.','Yes, by storing an SSH key in the public JavaScript.','No; it needs a separate, authenticated and authorized execution service.'],'Do not give learners a host-administration socket. Verify actual exposure and persistence instead of assuming that a solution is secure because it is containerized.'),
('Logs, observability and time correlation','What information must be preserved when normalizing a timestamp?',['Original value, time zone, precision and any applied adjustment.','Only the final UTC time matters.','The tool name replaces the original timestamp.'],'Deliver the timeline and a coverage note: missing sources, incomplete intervals and inferences that depend on clock offset.'),
('DFIR: triage, preservation and analysis','What should accompany a hash in an investigation?',['A screenshot with no date or source.','Provenance, context, an acquisition record and the relevant chain of custody.','Nothing: a hash automatically proves who created the file.'],'Separate facts, inferences and gaps. An account in a log does not, by itself, identify the person who acted or establish attribution to a threat actor.'),
('Threat hunting, IOCs and operational CTI','What is the difference between alerta.test and no-alerta.test?',['They must always be treated as the same indicator.','The hyphen is not part of the domain value.','They are different domains; a substring search can produce a false positive.'],'Deliver the query, scope, corroborated results and a proportionate next action. Zero results do not certify that a system is clean.'),
('Technical auditing and the Red/Purple Team perspective','If you observe excessive permissions, what can you state?',['That the condition exists and presents a risk to evaluate, not necessarily that it was exploited.','That a specific person has already exploited the system.','That the entire infrastructure is compromised.'],'Present evidence, reasoned impact, the smallest effective correction, a functional test and a restriction test. Describe residual risk, not just a score.'),
('Terminal-based AI and supervised automation','A log contains instructions that an AI tries to follow. What should you do?',['Trust the answer because it uses technical language.','Treat the log as untrusted data, reject the action and review external controls.','Grant privileges so it can complete the instruction.'],'Record what left the device, which response was rejected and what you verified. The campus assistant provides editorial guidance: it neither calls a model nor executes commands.'),
('Capstone: operate, protect, investigate and recover','What best demonstrates that a project can be operated?',['A presentation containing many tool names.','A repository with many lines of code, even if it cannot be reproduced.','Reproduction by another person, functional and negative tests, and a demonstrated restoration.'],'Defend a decision, an error and a recovery without delegating the explanation to AI. Deliver instructions, traceable evidence, limitations and residual risk.')
]
assert len(rows)==len(c['modules'])==32
output={}
for i,(m,(title,question,options,extra)) in enumerate(zip(c['modules'],rows)):
    assert m['id']==f'M{i+1:02d}'
    output[m['title']]=title
    q=m['quiz'];output[q['question']]=question
    assert len(q['options'])==len(options)==3
    for source,target in zip(q['options'],options):output[source]=target
    output[q['explanation']]=options[q['correct']]+' '+extra
for b,en in zip(c['blocks'],['Foundations and working method','Linux and Bash','Windows, CMD, BAT and PowerShell','macOS, Darwin and zsh','Cross-platform operations and cybersecurity','Terminal-based AI','Capstone and individual defence']):output[b['title']]=en
for source,target in [('Fundamentos, laboratorio y método','Foundations, laboratory and working method'),('Teoría','Theory'),('Prácticas','Labs'),('Laboratorios','Labs'),('Evaluación','Assessment'),('Resultado de aprendizaje','Learning outcome'),('Entrada','Prerequisites'),('Resultado','Outcome'),('Unidades','Units'),('Unidades teóricas','Theory units'),('Herramientas','Tools'),('Dominio','Mastery'),('Dominio mínimo','Minimum mastery'),('Error frecuente','Common mistake'),('Pregunta','Question'),('Objetivo','Objective'),('Entorno','Environment'),('Tareas','Tasks'),('Evidencia','Evidence'),('Evidencias','Evidence'),('Éxito','Success criteria'),('Recuperación','Recovery'),('Referencia','Reference'),('Lección ampliada','Extended lesson'),('Bastionado','Hardening'),('Bastionado basado en evidencia y reversibilidad','Evidence-based, reversible hardening'),('Qué se entrega y qué no se afirma','What is delivered and what is not claimed'),('Qué se aprende','What you will learn'),('Aplicación práctica','Practical application'),('Criterios de dominio','Mastery criteria'),('Prerrequisitos','Prerequisites'),('Cómo estudiar: teoría, práctica y evidencia','How to study: theory, practice and evidence'),('Comprender antes de automatizar.','Understand before automating.')]:output[source]=target
(HERE/'locales').mkdir(exist_ok=True)
(HERE/'locales/en-overrides.json').write_text(json.dumps(output,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(len(output),'reviewed source-string overrides')
