/** Path-scoped, read-only Cloudflare Worker. No origin proxy, accounts or telemetry. */
export const PREFIX = '/introduccion-dpd';
export const CSP = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; worker-src 'none'";

function secure(response, method = 'GET') {
  const headers = new Headers(response.headers);
  headers.set('Content-Security-Policy', CSP);
  headers.set('X-Content-Type-Options', 'nosniff');
  headers.set('Referrer-Policy', 'no-referrer');
  headers.set('X-Frame-Options', 'DENY');
  headers.set('Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=(), usb=()');
  headers.set('Cache-Control', response.status >= 400 || response.headers.get('Cache-Control') === 'no-store' ? 'no-store' : 'no-cache');
  headers.delete('Set-Cookie');
  headers.delete('Access-Control-Allow-Origin');
  const noBody = method === 'HEAD' || [204, 205, 304].includes(response.status);
  return new Response(noBody ? null : response.body, {status: response.status, headers});
}
function text(message, status, headers = {}) {
  return new Response(message, {status, headers: {'Content-Type': 'text/plain; charset=utf-8', ...headers}});
}
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const method = request.method;
    const reply = response => secure(response, method);
    if (url.pathname !== PREFIX && !url.pathname.startsWith(PREFIX + '/')) {
      return reply(text('Not found', 404));
    }
    if (!['GET', 'HEAD'].includes(method)) {
      return reply(text('Method not allowed', 405, {'Allow': 'GET, HEAD'}));
    }
    // URLs generated by this site use ASCII filenames only. Reject ambiguous encodings.
    if (/%|\\|[^A-Za-z0-9_./-]/.test(url.pathname) ||
        url.pathname.split('/').some(part => part.startsWith('.')) || url.pathname.includes('//')) {
      return reply(text('Not found', 404));
    }
    if (url.pathname === PREFIX) {
      return reply(new Response(null, {status: 308, headers: {Location: PREFIX + '/' + url.search}}));
    }
    if (!env?.ASSETS?.fetch) return reply(text('Asset binding unavailable', 503));
    const health = url.pathname === PREFIX + '/healthz';
    const asset = new URL(request.url);
    asset.search = ''; // No queries, cookies or authorization forwarded to static storage.
    asset.pathname = health ? PREFIX + '/_release.json' :
      url.pathname.endsWith('/') ? url.pathname + 'index.html' : url.pathname;
    const headers = new Headers();
    if (!health) for (const key of ['Accept', 'If-None-Match', 'If-Modified-Since', 'Range', 'If-Range']) {
      if (request.headers.has(key)) headers.set(key, request.headers.get(key));
    }
    try {
      const result = await env.ASSETS.fetch(new Request(asset, {method: health ? 'GET' : method, headers}));
      if (health) {
        if (result.status !== 200) return reply(text('Release metadata unavailable', 503));
        const release = await result.json();
        if (release.application !== 'introduccion-dpd' || !release.treeSha256) {
          return reply(text('Invalid release metadata', 503));
        }
        return reply(Response.json({status: 'ok', ...release}, {headers: {'Cache-Control': 'no-store'}}));
      }
      // html_handling=none means ASSETS must not redirect outside the mounted prefix.
      if (result.status >= 300 && result.status < 400 && result.status !== 304) {
        return reply(text('Unexpected asset redirect', 502));
      }
      return reply(result);
    } catch {
      return reply(text('Asset service unavailable', 503));
    }
  }
};
